image: node:16-alpine

stages:
  - update-production

deploy:
  stage: update-production
  only:
    - main
  script:
    - sudo npm i -g @liara/cli@3
    - liara deploy --app ticket-frontend --api-token $LIARATOKEN --detach