image: node:16-alpine

stages:
  - update-production

deploy:
  stage: update-production
  only:
    - main
  script:
    - npm i -g @liara/cli@3
    - liara deploy --app ticket-front --api-token $TOKEN --detach